import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { NavTopBar } from "@/components/nav-top-bar";import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <main className="h-screen w-screen flex flex-col">
          <NavTopBar />
          <Separator className={cn("bg-slate-700 dark:bg-slate-500")}/>
          {children}
          </main>
        </Providers>
        </body>
    </html>
  );
}
